project:
  type: website
  output-dir: docs

website:
  title: "CSC 380"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Course Content
        contents:
          - text: "Week 1"
            file: Course_Content/Week_1/home.qmd

          - text: "Week 2"
            file: Course_Content/Week_2/home.qmd

          - text: "Week 3"
            file: Course_Content/Week_3/home.qmd

          - text: "Week 4 & 5"
            file: Course_Content/Week_4&5/home.qmd

          - text: "Week 6"
            file: Course_Content/Week_6/home.qmd
          
          - text: "Week 7"
            file: Course_Content/Week_7/home.qmd

          - text: "Week 8"
            file: Course_Content/Week_8/home.qmd

          - text: "Week 9"
            file: Course_Content/Week_9/home.qmd

      - section: "Homework"
        contents:

          - text: "HW1: Probability"
            file: Homework/1/HW.qmd

          - text: "HW2: Data Collection"
            file: Homework/2/HW.qmd

          - text: "HW3: Data Exploration, Viz and Supervised ML"
            file: Homework/3/HW.qmd
            
      - section: "Ethics Discussions"
        contents:

          - text: "Political Content"
            file: Ethics/Week_2.qmd

          - text: "Creative Work"
            file: Ethics/Week_3.qmd

          - text: "Mental Health Support"
            file: Ethics/Week_4.qmd

          - text: "Recommendations"
            file: Ethics/Week_6.qmd

          - text: "Autonomous Driving"
            file: Ethics/Week_7.qmd

          - text: "Housekeeping"
            file: Ethics/Week_8.qmd
            

          - text: "Facial Recognition"
            file: Ethics/Week_9.qmd
            
      
      - section: "Bonus Questions"
        contents:

          - text: "Home"
            file: Bonus/home.qmd

      - text: "Participation"
        file: Participation_Activities/home.qmd

      - section: "Honors"
        contents:

          - text: "Assignments"
            file: Honors/home.qmd

      - section: "Syllabus"
        contents:
          - text: "Key Info"
            file: Syllabus/Key_Info.qmd

          - text: "Official Syllabus"
            file: Syllabus/Syllabus.qmd

      


format:
  html:
    theme: 
      - lux
      - custom.scss
    css: styles.css
    toc: true



