#  Week 3 : Data Collection and Data Processing, Exploratory Analysis 

## Objectives

### Course Objectives:

- [ ] Understand the fundamental concepts and principles of data science, including data collection, preprocessing, analysis, and interpretation. 
- [ ] Apply data analysis and visualization techniques to derive insights from diverse datasets.
- [ ] Develop proficiency in using data science tools and programming languages.
- [ ] Explore the ethical considerations associated with data-driven decision-making.

### Learning Outcomes:

- [ ] Convert a raw data source into a version appropriate for downstream analysis using Python.
- [ ] Demonstrate awareness of bias and ethics in data science.

<br>

## Lectures

[3.1 - Introduction to Pandas](1/home.qmd)

[3.2 - Data Collection (Part 1 of 2) ](2/home.qmd)

[3.3 - Data Collection (Part 2 of 2) & Data Processing (Part 1)](3/home.qmd)

<br>

## Activities

**Homework**

- [x] [Homework 1: Due 5 pm, June 26th,Monday](../../Homework/1/HW.qmd)

**Weekly Checkin**

- [x] Weekly Checkin for Week 2 : Due 5 pm, June 25th, Sunday.
- [ ] Weekly Checkin for Week 3 : Due 5 pm, July 2, Sunday



## Summary ( Plan versus Achievements):

* Strikethrough text is changes in plan.
* Green is new items added after planning.
* Checked boxes are completed items.

### Week 3 ( June 18 to <s>June 25</s> June 27)

### Lectures


- [ ] <s>Topic: Statistics and Probability - Lecture 4 (Part 2)</s> Will continue in Week 8
- [x] <span style="color:green;">Lecture 2.x.1 Binomial Distribution</span>
- [x] Topic: Data processing and exploratory Analysis ( 2 or 3 Lectures ):
    - [x] 3.1 - Introduction to Pandas
    - [x] 3.2 - Data Collection (Part 1 of 2)
    - [x] 3.3 - Data Collection (Part 2 of 2) & Data Processing (Part 1)

### Homeworks

- [x] Homework 1 due <s>June 25</s> June 26, 5 pm
    * Homework 1 Question 3.2 dropped. 

### Weekly Check-in

- [x] Check-in for week 2 is due on June 25, 5 pm.
- [x] Check-in for week 3 opens.

### Assigned Reading

- [x] Week 3's assigned reading will be announced and available on D2L on or before Monday.


