# Week 3 : AI in Creative Work 

## Reading

- [‘Black Mirror’ Creator Says ChatGPT Wrote a ‘S—‘ Episode When He Tested It: No ‘Real Original Thought’](https://www.thewrap.com/black-mirror-creator-charlie-brooker-chat-gpt-episode/)

- [TV’s War With the Robots Is Already Here](https://www.nytimes.com/2023/05/10/arts/television/writers-strike-artificial-intelligence.html)

<br>

## Question for Discussion 

Disclaimer : There are no write or wrong answers below. Write your opinion on the topic.

In the article, we see the lines "Because all it's done is look up all the synopses of 'Black Mirror' episodes, and sort of mush them together. Then if you dig a bit more deeply you go, 'Oh, there's not actually any real original thought here". We also see that "The chatbot, created by developer OpenAI, is a large language model, meaning it only mimics the large quantities of pre-existing texts it consumes from across the internet."

* If a chatbot/a large language model like ChatGPT writes a book, who do you think should get the copyright to the story ? What if the book won an award? Who wins the award?  The AI itself? The company that owns the AI? The person who gave prompts to the chatbot to create the book?  Can something like this even be copyrighted? What is your opinion?


* If the creative content a model creates is it mimicking "the large quantities of pre-existing texts it consumes from across the internet" and often contains "no original thought", is it plagiarism? Why/Why not?

* Do you think the writer's worry is warranted?
