# Sonam's Dilemma: A Gift for Few or a Chance for All
###### Bonus Question : 1 point 

<br>

### Instructions

- Due Date : July 7, Friday, 5 pm
- Submit your answer at D2 > Quiz > "Sonam's Dilemma : a gift for few or a chance for all"

### Question
<br>
_Source : Story I made up, text improved by ChatGPT, and then edited by myself._

Once upon a time, in the grand kingdom of Razia, there existed a mesmerizing lead dancer named Sonam. She possesed a combination of charm, extraordinary talent, and intelligence that made her stand out amongst her peers. Sonam's passion for dance was matched only by her love for her dance group,with 2000 other talented dances, who all shared an unbreakable bond and admired their noble Queen above all.

One fine day, as Sonam's heart overflowed with gratitude for their benevolent ruler, she decided to express her deep admiration through the power of music. She crafted a beautiful song that portrayed the love and adoration her dance group held for Queen Razia. With eager anticipation, Sonam's troupe dedicated themselves to perfecting their dance moves to match the rhythm and emotion of her heartfelt composition.

The auspicious occasion of Queen Razia's birthday arrived, filling the grand palace with a sense of joy and celebration. The Queen, known for her discerning taste and appreciation for the arts, eagerly awaited the performance of Sonam's dance group. As the music began to play and the dancers gracefully glided across the grand ballroom, a spell was cast upon all those in attendance.

The Queen was captivated by the talent displayed before her, and her heart swelled with pride and delight. She could not help but marvel at the synchronized movements and the sheer passion that emanated from each and every member of the dance group. As the performance reached its crescendo, Queen Razia's decision was made in an instant—this remarkable group deserved a gift to commemorate their extraordinary dedication.

<div class="Secret"> <Dr_Cynthia_Breazeal></Dr_Cynthia_Breazeal> </div>

However, there were only a limited number of gift available to give out right now. She presented Sonam with two choices, each with its own intriguing possibilities. The first option was straightforward : 660 randomly chosen dancers would receive a gift. This meant that a select few would be rewarded, leaving the remaining members without a token of appreciation.

The second choice, however, offered a twist. Queen Shah proposed distributing the available gifts among all dancers, but with a twist of uncertainty. Each dancer would have a 33% chance of receiving a gift and a 66% chance of going without. 

Now faced with this dilemma, Sonam's sharp mind began to evaluate the situation. Which option should Sonam pick? Why? Why not the other?
