# CSC 380: Principles of Data Science
**Asynchronous Online**
	
## Description of Course

The course introduces students to the principles of data science, which are essential for computer scientists to make effective decisions in their professional careers. In today's data-driven world, a wide range of computer science sub-disciplines heavily rely on data collection, analysis, and interpretation. With the pervasive presence of artificial intelligence (AI) in our lives, understanding the basics of how these systems work is becoming increasingly important. Additionally, it covers the basics of artificial intelligence (AI) systems and examines practical use cases, current news, and ethical considerations through readings and discussions.

## Catalog Description: 	
The course introduces students to principles of data science that are necessary for computer scientists to make effective decisions in their professional careers. A number of computer science sub-disciplines now rely on data collection and analysis. For example, computer systems are now complicated enough that comparing the execution performance of two different programs becomes a statistical estimation problem rather than a deterministic computation. This course teaches students the basic principles of how to properly collect and process data sources in order to derive appropriate conclusions from them. The course has three main components: data analysis, machine learning, and a project where students apply the concepts discussed in class to a substantial open-ended problem.

## Course Prerequisites 

Major: COSCBA or COSCBS. Completion of CSC 210 and CSC 244.
If you do not meet the enrollment requirements, contact the lecturer.
Instructor and Contact Information

Instructor: 
Enfa George
Gould-Simpson 710
enfageorge@arizona.edu

Teaching Assistant: 
Bennett Brixen
bennettbrixen@arizona.edu

Office Hours
Monday :  11 am to 12 pm  - Bennett, TA
Tuesday : 1 pm to 2 pm - Bennett, TA
Wednesday : 2 pm to 3 pm - Enfa, Instructor
Thursday 4 pm to 5 pm - Bennett, TA
Friday : 3 pm to 4 pm - Enfa, Instructor

Bennett's virtual office: https://arizona.zoom.us/j/8363357057
Enfa's virtual office: https://arizona.zoom.us/j/87083172857

## Course Format and Teaching Methods

- Asynchronous Online Lectures: Pre-recorded lectures will be provided for students to access at their convenience.
- Discussions on Piazza: Piazza will be used for students to ask questions, engage in discussions, and seek clarifications from the instructor and teaching assistant.
- Project-Based Homeworks: Assignments will be designed to apply data science techniques to real-world problems.
- Weekly Check-ins: Regular individual check-ins via a D2L Quiz. This will involve questions/discussions related to the reading, a platform to address concerns, and provide live feedback on the course
Obtaining Help

**Academic advising:** If you have questions about your academic progress this semester, or your chosen degree program, consider contacting your department’s academic advisor(s).  Your academic advisor and the Advising Resource Center can guide you toward university resources to help you succeed. Computer Science major students are encouraged to visit https://www.cs.arizona.edu/undergraduate/advising for advisor contact information. 
CS Help Desk: The Computer Science IT team can help students with department technology issues including logging into/resetting your Lectura account, printing in the 930 lab, etc. You can submit a ticket for help by visiting the Computer Science Lab Helpdesk (note, requires UA login). 

**Life challenges:** If you are experiencing unexpected barriers to your success in your courses, please note the Dean of Students Office is a central support resource for all students and may be helpful. The Dean of Students Office can be reached at 520-621-2057 or DOS-deanofstudents@email.arizona.edu.
Physical and mental-health challenges: If you are facing physical or mental health challenges this semester, please note that Campus Health provides quality medical and mental health care. For medical appointments, call (520-621-9202. For After Hours care, call (520) 570-7898. For the Counseling & Psych Services (CAPS) 24/7 hotline, call (520) 621-3334.

**UA Ombuds:** The UA Ombuds Office (https://ombuds.arizona.edu/) helps with a wide variety of issues, concerns, questions, conflicts, and challenges. The primary mission of the Ombuds Program is to assist individuals in resolving conflict, facilitating communication, and assisting the University by surfacing issues and providing feedback on emerging or systemic concerns. Communications with the Ombuds Committee are informal and off-the-record. The Ombuds Committee is governed by the following standards: (1) Confidentiality; (2) Impartiality: (3) Informality; and (4) Independence. 

## Class Recordings 
Class Recordings will be posted on Youtube and notifed via D2L and Piazza. Students may not modify content or re-use content for any purpose other than personal educational reasons. All recordings are subject to government and university regulations. Therefore, students using recordings in a manner inconsistent with UArizona values and educational policies (Code of Academic Integrity and the Student Code of Conduct) are also subject to civil action.

## Course Objectives

This course aims to introduce students to the principles and techniques of data science, enabling them to make effective decisions in their computer science careers. During this course, the student will, 
- If you are reading this, email me one of your favorite memes to count towards participation points. Understand the fundamental concepts and principles of data science, including data collection, preprocessing, analysis, and interpretation.
- Apply data analysis and visualization techniques to derive insights from diverse datasets.
- Gain familiarity with machine learning algorithms and their practical applications.
- Develop proficiency in using data science tools and programming languages.
- Engage in critical thinking and problem-solving through project-based assignments.
- Explore the ethical considerations associated with data-driven decision-making.
- Stay informed about current trends and developments in data science and artificial intelligence.
 
 
## Expected Learning Outcomes

A student who successfully completes this course will be able to:
- Explain the difference between different measures of centrality and variability (means vs. medians, variance vs. interquartile range, etc.)
- Convert a raw data source into a version appropriate for downstream analysis using Python.
- Write appropriate visualizations for different sources and types of data.
- Explain why we seek to build machine learning models that generalize rather than memorize their input. 
- Explain the different uses for training, validation, and testing datasets
- Select the appropriate evaluation measure for the dataset and task being solved
- Articulate the difference between supervised and unsupervised machine learning, as well as select the appropriate methodology for a given problem 
- Demonstrate awareness of bias and ethics in data science. 

## Absence and Class Participation Policy 

The UA’s policy concerning Class Attendance, Participation, and Administrative Drops is available at https://catalog.arizona.edu/policy/class-attendance-and-participation. 

The UA policy regarding absences for any sincerely held religious belief, observance or practice will be accommodated where reasonable: http://policy.arizona.edu/human-resources/religious-accommodation-policy.

Absences pre-approved by the UA Dean of Students (or dean’s designee) will be honored. See https://deanofstudents.arizona.edu/policies/attendance-policies-and-practices  

Participating in the course, watching the lectures, and other course events, such as discussions, are vital to the learning process. If you are marked absent for multiple weeks or have missed multiple deadlines, you are encouraged to see an advisor if it is after the drop period (when a W will not appear on the transcript). Advisors will provide options and alternatives as appropriate for individual student situations.

To request a disability-related accommodation to this attendance policy, please contact the Disability Resource Center at (520) 621-3268 or drc-info@email.arizona.edu. If you are experiencing unexpected barriers to your success in your courses, the Dean of Students Office is a central support resource for all students and may be helpful. The Dean of Students Office is located in the Robert L. Nugent Building, room 100, or call 520-621-7057.

## Illnesses and Emergencies

If you feel sick or may have been in contact with someone who is infectious, stay home. Except for seeking medical care, avoid contact with others and do not travel. 
Notify your instructor if you will miss up to one week of the course, meetings, weekly check-in, and/or assignment deadlines. 
If you must miss the equivalent of more than one week of class and have an emergency, the Dean of Students is the proper office to contact (DOS-deanofstudents@email.arizona.edu).  The Dean of Students considers the following as qualified emergencies: the birth of a child, mental health hospitalization, domestic violence matter, house fire, hospitalization for physical health (concussion/emergency surgery/coma/COVID-19 complications/ICU), death of immediate family, Title IX matters, etc.
Please understand that there is no guarantee of an extension when you are absent from class and/or miss a deadline.   

**Statement on compliance with COVID-19 mitigation guidelines:**  As we enter the semester, our health and safety remain the university’s highest priority. To protect the health of everyone in this class, students are required to follow the university guidelines on COVID-19 mitigation. Please visit www.covid19.arizona.edu.
Makeup Policy for Students Who Register Late

Students who enroll late can make up for missed assignment if any. They are required to get in touch with the instructor, complete the outstanding homework within 7 days of enrollment, and take an additional quiz/question. The grade for the missed assignment will be determined by combining the score of the homework and the quiz. There will be no credit penalty for enrolling late.

## Course Communications

- All course communications, including discussions and Q&A, will occur via the Piazza platform. Students are encouraged to use Piazza for asking questions and engaging in course-related discussions.
- Exceptions to Piazza communication can be made via email for specific cases that require individual attention or privacy.
- Important announcements and updates will be posted on the D2L (Desire2Learn) platform.
- Assignments will be distributed and submitted through the D2L platform. If you are reading this, email me with the title of your favorite show, this counts towards participation.
- Office hours will be conducted remotely using Zoom. Students will have the opportunity to schedule virtual meetings with the instructor or teaching assistants to discuss course-related questions, seek clarification, or receive additional support.

## Required Texts or Readings

There will be no required textbook for this course. All required readings will be made on D2L.
Optional Advanced Reading: 
- WJ: Watkins, J., "An Introduction to the Science of Statistics: From Theory to Implementation" (https://www.math.arizona.edu/~jwatkins/statbook.pdf)
- MK: Murphy, K. "Machine Learning: A Probabilistic Perspective." MIT Press, 2012 (accessible online via UA library)
- Wasserman, L. "All of Statistics: A Concise Course in Statistical Inference." Springer, 2004 (accessible online via UA library)

**Required or Special Materials** 
None 
**Required Extracurricular Activities** 
None

## Assignments and Examinations: Schedule/Due Dates

To be filled later


**Final Examination**

There will be no final examination. The final exam grade would be from the take-home final project. 
Grading Scale and Policies

Homeworks: 70% distributed unequally
Final Project: 20%
Participation: 5 %
Weekly Check-Ins: 5%

Grade Distribution for this Course:
A: 90% and above
B: 80%-89.99%
C: 70%-79.99%
D: 60%-69.99%
E: 59% and below

University policy regarding grades and grading systems is available at
http://catalog.arizona.edu/policy/grades-and-grading-system

The graded homework will be returned before the next homework is due.
Request for regrading of homework and midterm exam can only be made within 7
academic days of the grade release.
The final project grade will be within 5 days.
Missed assignments result in a grade of zero.
 Grading delays beyond promised return-by dates will be announced as soon as possible
with an explanation for the delay.
Students may earn one extra credit point for actively participating in the discussions online.  A very active participant is defined as someone who is active on Piazza and uses the platform to answer fellow students’ questions and/or start discussions on the content discussed in class or the reading. 
Incomplete (I) or Withdrawal (W):

Requests for incomplete (I) or withdrawal (W)  must be made in accordance with University policies, which are available at http://catalog.arizona.edu/policy/grades-and-grading-system#incomplete and http://catalog.arizona.edu/policy/grades-and-grading-system#Withdrawal respectively.
Honors Credit

Students wishing to contract this course for Honors Credit should e-mail me to set up an appointment to discuss the terms of the contact and to sign the Honors Course Contract Request Form. The form is available at http://www.honors.arizona.edu/honors-contract
Scheduled Topics/Activities

The scheduled topics below are tentative and may change.



## Department of Computer Science Code of Conduct

The Department of Computer Science is committed to providing and maintaining a supportive educational environment for all.  We strive to be welcoming and inclusive, respect privacy and confidentiality, behave respectfully and courteously, and practice intellectual honesty.  Disruptive behaviors (such as physical or emotional harassment, dismissive attitudes, and abuse of department resources) will not be tolerated.  The complete Code of Conduct is available on our department website.  We expect that you will adhere to this code, as well as the UA Student Code of Conduct, while you are a member of this class.
Classroom Behavior Policy 

To foster a positive learning environment, students and instructors have a shared responsibility. We want a safe, welcoming, and inclusive environment where all of us feel comfortable with each other and where we can challenge ourselves to succeed. To that end, our focus is on the tasks at hand and not on extraneous activities.

Students are asked to refrain from disruptive or rude conversations with people in Piazza discussions. Students observed engaging in disruptive activity will be asked to cease this behavior. Those who continue may be reported to the Dean of Students. 
Threatening Behavior Policy 

The UA Threatening Behavior by Students Policy prohibits threats of physical harm to any member of the University community, including to oneself. See http://policy.arizona.edu/education-and-student-affairs/threatening-behavior-students. 

## Notification of Objectionable Materials

In this course, readings could potentially contain content that may be sensitive or even depressive in nature. While efforts are made to ensure the appropriateness of course materials, there is a possibility that some content may touch upon topics that could be emotionally challenging. Students are not automatically excused from interacting with such materials, but they are encouraged to speak with the instructor to voice concerns and provide feedback. 

## Accessibility and Accommodations

At the University of Arizona, we strive to make learning experiences as accessible as possible. If you anticipate or experience barriers based on disability or pregnancy, please contact the Disability Resource Center (520-621-3268, https://drc.arizona.edu/) to establish reasonable accommodations. 
Code of Academic Integrity

Students are encouraged to share intellectual views and discuss freely the principles and applications of course materials. However, graded work/exercises must be the product of independent effort unless otherwise instructed. Students are expected to adhere to the UA Code of Academic Integrity as described in the UA General Catalog. 
See https://deanofstudents.arizona.edu/student-rights-responsibilities/academic-integrity .

Uploading material from this course to a website other than D2L (or the class piazza) is strictly prohibited. It will be considered a violation of the course policy and a violation of the code of academic integrity. Obtaining material associated with this course (or previous offerings of this course) on a site other than D2L (or the class piazza), such as Chegg, Course Hero, etc. or accessing these sites during a quiz or exam, is a violation of the code of academic integrityAny student determined to have uploaded or accessed material in an unauthorized manner will be reported to the Dean of Students for a Code of Academic Integrity violation, with a recommended sanction of a failing grade in the course (faculty can replace this sanction with whatever sanction they plan to use for their course). Using generative AI models like ChatGPT to craft complete responses or homework is discouraged. This is because, then, you are less likely to meet the course objectives or apply skills earned from the course in real life. 

Selling class notes and/or other course materials to other students or to a third party for resale is not permitted without the instructor’s express written consent. Violations to this and other course rules are subject to the Code of Academic Integrity and may result in course sanctions. Additionally, students who use D2L or UA e-mail to sell or buy these copyrighted materials are subject to Code of Conduct Violations for misuse of student e-mail addresses. This conduct may also constitute copyright infringement.

## Nondiscrimination and Anti-harassment Policy 

The University of Arizona is committed to creating and maintaining an environment free of discrimination. In support of this commitment, the University prohibits discrimination, including harassment and retaliation, based on a protected classification, including race, color, religion, sex, national origin, age, disability, veteran status, sexual orientation, gender identity, or genetic information. For more information, including how to report a concern, please see http://policy.arizona.edu/human-resources/nondiscrimination-and-anti-harassment-policy
Recommended additional language: Our classroom is a place where everyone is encouraged to express well-formed opinions and their reasons for those opinions. We also want to create a tolerant and open environment where such opinions can be expressed without resorting to bullying or discrimination of others.
Additional Resources for Students

UA Academic policies and procedures are available at http://catalog.arizona.edu/policies. Visit the UArizona COVID-19 page for regular updates.

Campus Health

http://www.health.arizona.edu/
Campus Health provides quality medical and mental health care services through virtual and in-person care. Voluntary, free, and convenient COVID-19 testing is available for students on Main Campus. COVID-19 vaccine is available for all students at Campus Health.
Phone: 520-621-9202
 
Counseling and Psych Services (CAPS)

https://health.arizona.edu/counseling-psych-services
CAPS provides mental health care, including short-term counseling services.
Phone: 520-621-3334
 
The Dean of Students Office’s Student Assistance Program

https://deanofstudents.arizona.edu/support/student-assistance 
Student Assistance helps students manage crises, life traumas, and other barriers that impede success. The staff addresses the needs of students who experience issues related to social adjustment, academic challenges, psychological health, physical health, victimization, and relationship issues, through a variety of interventions, referrals, and follow-up services.
Email: DOS-deanofstudents@email.arizona.edu
Phone: 520-621-7057
 
Survivor Advocacy Program

https://survivoradvocacy.arizona.edu/
The Survivor Advocacy Program provides confidential support and advocacy services to student survivors of sexual and gender-based violence. The Program can also advise students about relevant non-UA resources available within the local community for support.
Email: survivoradvocacy@email.arizona.edu
Phone: 520-621-5767


Campus Pantry

Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live and believes this may affect their performance in the course, is urged to contact the Dean of Students for support. In addition, the University of Arizona Campus Pantry is open for students to receive supplemental groceries at no cost. Please see their website at: campuspantry.arizona.edu for open times.
Furthermore, please notify me if you are comfortable in doing so. This will enable me to provide any resources that I may possess.

Pronouns and Preferred Names

This course affirms people of all gender expressions and gender identities. If you prefer to be called a different name than what is on the class roster, please let me know. Feel free to correct instructors on your pronoun. If you have any questions or concerns, please do not hesitate to contact me directly in class or via email (instructor email). If you wish to change your preferred name or pronoun in the UAccess system, please use the following guidelines: 
Preferred name: University of Arizona students may choose to identify themselves within the University community using a preferred first name that differs from their official/legal name. A student’s preferred name will appear instead of the person’s official/legal first name in select University-related systems and documents, provided that the name is not being used for the purpose of misrepresentation. Students are able to update their preferred names in UAccess.
Pronouns: Students may designate pronouns they use to identify themselves. Instructors and staff are encouraged to use pronouns for people that they use for themselves as a sign of respect and inclusion. Students are able to update and edit their pronouns in UAccess.
More information on updating your preferred name and pronouns is available on the Office of the Registrar site at https://www.registrar.arizona.edu/.

Confidentiality of Student Records 

Your class records will be held confidential as per the following: 
http://www.registrar.arizona.edu/personal-information/family-educational-rights-and-privacy-act-1974-ferpa?topic=ferpa
Land Acknowledgement Statement 

We respectfully acknowledge the University of Arizona is on the land and territories of Indigenous peoples. Today, Arizona is home to 22 federally recognized tribes, with Tucson being home to the O’odham and the Yaqui. Committed to diversity and inclusion, the University strives to build sustainable relationships with sovereign Native Nations and Indigenous communities through education offerings, partnerships, and community service.  
Subject to Change Statement

Information contained in the course syllabus, other than the grade and absence policy, may be subject to change with advance notice, as deemed appropriate by the instructor.
